services:
  postgres:
    image: postgres:15
    container_name: postgres_blogs
    volumes:
      - blogs_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=supersafe
    ports:
      - 5432:5432

volumes:
  blogs_db: